title: Kristoffer Ian Cosme
description: "Enterprise Data Management Portfolio"
theme: jekyll-theme-minimal
logo: "Image/Screenshot_2025-03-15-20-23-53-709_com.miui.gallery-edit.jpg"

show_downloads: true

